export enum EnumCartAction {
  UPDATE_ITEM_START = 'UPDATE_ITEM_START',
  UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS',
  UPDATE_ITEM_FILL = 'UPDATE_ITEM_FILL',

  DELETE_ITEM_START = 'DELETE_ITEM_START',
  DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCES',
  DELETE_ITEM_FILL = 'DELETE_ITEM_FILL',
  MY_CART_START = 'MY_CART_START',
  MY_CART_SUCCESS = 'MY_CART_SUCCES',
  MY_CART_FILL = 'MY_CART_FILL',
}
