export enum EnumAdminAction {
  GET_ALL_USER_START = 'GET_ALL_USER_START',
  GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS',
  GET_ALL_USER_FILL = 'GET_ALL_USER_FILL',

  GET_USER_BY_ID_START = 'GET_USER_BY_ID_START',
  GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FILL = 'GET_USER_BY_ID_FILL',

  DELETE_USER_START_START = 'DELETE_USER_START_START',
  DELETE_USER_START_SUCCESS = 'DELETE_USER_START_SUCCESS',
  DELETE_USER_START_FILL = 'DELETE_USER_START_FILL',

  UPDATE_USER_START = 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FILL = 'UPDATE_USER_FILL',

  CREATE_PRODUCTS_START = 'CREATE_PRODUCTS_START',
  CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS',
  CREATE_PRODUCTS_FILL = 'CREATE_PRODUCTS_FILL',

  UPDATE_PRODUCTS_START = 'UPDATE_PRODUCTS_START',
  UPDATE_PRODUCTS_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS',
  UPDATE_PRODUCTS_FILL = 'UPDATE_PRODUCTS_FILL',

  DELETE_PRODUCTS_START = 'DELETE_PRODUCTS_START',
  DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS',
  DELETE_PRODUCTS_FILL = 'DELETE_PRODUCTS_FILL',
}
