export enum EnumAuthAction {
  USER_SIGHUP_SUCCESS = 'USER_SIGHUP_SUCCESS',
  USER_SIGHUP_START = 'USER_SIGHUP_START',
  USER_SIGHUP_FILL = 'USER_SIGHUP_FILL',

  USER_LOGIN_START = 'USER_LOGIN_START',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FILL = 'USER_LOGIN_FILL',

  USER_LOGOUT = 'USER_LOGOUT',
}
