export enum EnumOrderAction {
  GET_ORDER_BY_ID_START = 'GET_ORDER_BY_ID_START',
  GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS',
  GET_ORDER_BY_ID_FILL = 'GET_ORDER_BY_ID_FILL',

  GET_MY_ORDERS_START = 'GET_MY_ORDERS_START',
  GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS',
  GET_MY_ORDERS_FILL = 'GET_MY_ORDERS_FILL',

  CREATE_ORDER_START = 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FILL = 'CREATE_ORDER_FILL',

  GET_ORDERS_START = 'GET_ORDERS_START',
  GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS',
  GET_ORDERS_FILL = 'GET_ORDERS_FILL',

  UPDATE_DELIVER_ORDERS_START = 'UPDATE_DELIVER_ORDERS_START',
  UPDATE_DELIVER_ORDERS_SUCCESS = 'UPDATE_DELIVER_ORDERS_SUCCESS',
  UPDATE_DELIVER_ORDERS_FILL = 'UPDATE_DELIVER_ORDERS_FILL',
}
