export enum EnumUserAction {
  GET_PROFILE_USER_START = 'GET_PROFILE_USER_START',
  GET_PROFILE_USER_SUCCESS = 'GET_PROFILE_USER_SUCCESS',
  GET_PROFILE_USER_FILL = 'GET_PROFILE_USER_FILL',

  UPDATE_PROFILE_USER_START = 'UPDATE_PROFILE_USER_START',
  UPDATE_PROFILE_USER_SUCCESS = 'UPDATE_PROFILE_USER_SUCCESS',
  UPDATE_PROFILE_USER_FILL = 'UPDATE_PROFILE_USER_FILL',
}
