export enum EnumUserAction {
  GET_PROFILE_USER_START = 'GET_PROFILE_USER_START',
  GET_PROFILE_USER_SUCCESS = 'GET_PROFILE_USER_SUCCESS',
  GET_PROFILE_USER_FILL = 'GET_PROFILE_USER_FILL',

  UPDATE_PROFILE_USER_START = 'UPDATE_PROFILE_USER_START',
  UPDATE_PROFILE_USER_SUCCESS = 'UPDATE_PROFILE_USER_SUCCESS',
  UPDATE_PROFILE_USER_FILL = 'UPDATE_PROFILE_USER_FILL',

  GET_ALL_USERS_START = 'GET_ALL_USERS_START',
  GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL',

  GET_USER_BY_ID_START = 'GET_USER_BY_ID_START',
  GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL',
}
