export enum EnumProductsAction {
  GET_ALL_PRODUCTS_START = 'GET_ALL_PRODUCTS_START',
  GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS',
  GET_ALL_PRODUCTS_FILL = 'GET_ALL_PRODUCTS_FILL',

  GET_PRODUCTS_BY_ID_START = 'GET_PRODUCTS_BY_ID_START',
  GET_PRODUCTS_BY_ID_SUCCESS = 'GET_PRODUCTS_BY_ID_SUCCESS',
  GET_PRODUCTS_BY_ID_FILL = 'GET_PRODUCTS_BY_ID_FILL',

  GET_TOP_PRODUCTS_START = 'GET_TOP_PRODUCTS_START',
  GET_TOP_PRODUCTS_SUCCESS = 'GET_TOP_PRODUCTS_SUCCESS',
  GET_TOP_PRODUCTS_FILL = 'GET_TOP_PRODUCTS_FILL',

  GET_ALL_CATEGORY_START = 'GET_ALL_CATEGORY_START',
  GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS',
  GET_ALL_CATEGORY_FILL = 'GET_ALL_CATEGORY_FILL',

  GET_ALL_CATEGORY_NAME_START = 'GET_ALL_CATEGORY_NAME_START',
  GET_ALL_CATEGORY_NAME_SUCCESS = 'GET_ALL_CATEGORY_NAME_SUCCESS',
  GET_ALL_CATEGORY_NAME_FILL = 'GET_ALL_CATEGORY_NAME_FILL',

  ADD_REVIEW_TO_PRODUCT_START = 'ADD_REVIEW_TO_PRODUCT_START',
  ADD_REVIEW_TO_PRODUCT_SUCCESS = 'ADD_REVIEW_TO_PRODUCT_SUCCESS',
  ADD_REVIEW_TO_PRODUCT_FILL = 'ADD_REVIEW_TO_PRODUCT_FILL',
}
